// PROFILE
export const FETCH_PROFILE = 'FETCH_PROFILE';
// USERS
export const LIKE_USER = 'LIKE_USER';
// AUTH
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
// ERRORS
export const GET_ERRORS = 'GET_ERRORS';